[config]
response_language = "ja-JP"

[pr_description]
extra_instructions = "回答は全て日本語で行ってください。"

[pr_reviewer]
extra_instructions = "回答は全て日本語で行ってください。"

[pr_code_suggestions]
extra_instructions = "回答は全て日本語で行ってください。"
