name: Run PHPUnit

# pushした時とプルリクエストした時に動作
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    # backendのディレクトリを操作対象にする
    defaults:
      run:
        working-directory: ./backend

    steps:
    # GitHub のリポジトリからソースコードを Ubuntu マシン上にダウンロード
    - uses: actions/checkout@v4

    # PHPをセットアップ
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: none

    # 環境変数の準備
    - name: Copy .env
      run: cp .env.example .env

    # 依存関係のインストール
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    # キーの生成
    - name: Generate key
      run: php artisan key:generate

    # ディレクトリの権限を設定
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # テストの実行
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
